/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorymanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Add_items extends javax.swing.JFrame {

    /**
     * Creates new form Add_items
     */
    public Add_items() {
        initComponents();
    }
    
    //database connentivity
    static final String DB_URL = "jdbc:mysql://localhost:3306/inventory";
    static final String DB_DRV = "com.mysql.jdbc.Driver";
    static final String DB_USER = "user1";
    static final String DB_PASSWD = "User1db@123";

    Connection connection = null;
    //Statement statement = null;
    PreparedStatement pstm = null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        item_p1 = new javax.swing.JPanel();
        item_lbl_title = new javax.swing.JLabel();
        item_btn_dashbd = new javax.swing.JButton();
        item_p2 = new javax.swing.JPanel();
        item_lbl_id = new javax.swing.JLabel();
        item_lbl_name = new javax.swing.JLabel();
        item_lbl_Qnt = new javax.swing.JLabel();
        item_lbl_category = new javax.swing.JLabel();
        item_txt_id = new javax.swing.JTextField();
        item_txt_name = new javax.swing.JTextField();
        item_txt_price = new javax.swing.JTextField();
        item_spinner_qnt = new javax.swing.JSpinner();
        item_dropdown_category = new javax.swing.JComboBox<>();
        item_btn_add = new javax.swing.JButton();
        item_btn_edit = new javax.swing.JButton();
        item_btn_delete = new javax.swing.JButton();
        item_btn_reset = new javax.swing.JButton();
        item_lbl_price = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Item entry ");
        setBackground(new java.awt.Color(255, 255, 51));
        setName("item_frame"); // NOI18N
        setResizable(false);

        item_p1.setBackground(new java.awt.Color(255, 255, 153));
        item_p1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        item_p1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        item_p1.setName("item_p1"); // NOI18N

        item_lbl_title.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        item_lbl_title.setText("Item Entry");
        item_lbl_title.setName("item_lbl_title"); // NOI18N

        item_btn_dashbd.setBackground(new java.awt.Color(255, 204, 102));
        item_btn_dashbd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        item_btn_dashbd.setText("dashboard");
        item_btn_dashbd.setName("item_btn_dashbd"); // NOI18N
        item_btn_dashbd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_btn_dashbdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout item_p1Layout = new javax.swing.GroupLayout(item_p1);
        item_p1.setLayout(item_p1Layout);
        item_p1Layout.setHorizontalGroup(
            item_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, item_p1Layout.createSequentialGroup()
                .addContainerGap(302, Short.MAX_VALUE)
                .addComponent(item_lbl_title, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addGap(222, 222, 222)
                .addComponent(item_btn_dashbd)
                .addContainerGap())
        );
        item_p1Layout.setVerticalGroup(
            item_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, item_p1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(item_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item_lbl_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(item_btn_dashbd))
                .addContainerGap())
        );

        item_lbl_title.getAccessibleContext().setAccessibleName("item_lbl_title");

        item_p2.setBackground(new java.awt.Color(255, 255, 204));
        item_p2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        item_p2.setName("item_p3"); // NOI18N

        item_lbl_id.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        item_lbl_id.setText("Item Id");
        item_lbl_id.setName("item_lbl_id"); // NOI18N

        item_lbl_name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        item_lbl_name.setText("Item Name");
        item_lbl_name.setName("item_lbl_name"); // NOI18N

        item_lbl_Qnt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        item_lbl_Qnt.setText("Quantity");
        item_lbl_Qnt.setName("item_lbl_Qnt"); // NOI18N

        item_lbl_category.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        item_lbl_category.setText("Category");
        item_lbl_category.setName("item_lbl_category"); // NOI18N

        item_txt_id.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        item_txt_id.setName("item_txt_id"); // NOI18N

        item_txt_name.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        item_txt_name.setName("item_txt_name"); // NOI18N

        item_txt_price.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        item_txt_price.setName("item_txt_price"); // NOI18N

        item_spinner_qnt.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        item_spinner_qnt.setName("item_spinner_qnt"); // NOI18N

        item_dropdown_category.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        item_dropdown_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "\" \"", "Electronics", "Grocery", "Pharmacy", "Medical", "Instrument", "others" }));
        item_dropdown_category.setName("item_dropdown_category"); // NOI18N
        item_dropdown_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_dropdown_categoryActionPerformed(evt);
            }
        });

        item_btn_add.setBackground(new java.awt.Color(255, 204, 102));
        item_btn_add.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        item_btn_add.setText("Add item");
        item_btn_add.setName("item_btn_add"); // NOI18N
        item_btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_btn_addActionPerformed(evt);
            }
        });

        item_btn_edit.setBackground(new java.awt.Color(255, 204, 102));
        item_btn_edit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        item_btn_edit.setText("Edit item");
        item_btn_edit.setName("item_btn_edit"); // NOI18N
        item_btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_btn_editActionPerformed(evt);
            }
        });

        item_btn_delete.setBackground(new java.awt.Color(255, 204, 102));
        item_btn_delete.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        item_btn_delete.setText("Delete item");
        item_btn_delete.setName("item_btn_delete"); // NOI18N

        item_btn_reset.setBackground(new java.awt.Color(255, 204, 102));
        item_btn_reset.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        item_btn_reset.setText("Reset");
        item_btn_reset.setName("item_btn_reset"); // NOI18N

        item_lbl_price.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        item_lbl_price.setText("Price");

        javax.swing.GroupLayout item_p2Layout = new javax.swing.GroupLayout(item_p2);
        item_p2.setLayout(item_p2Layout);
        item_p2Layout.setHorizontalGroup(
            item_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item_p2Layout.createSequentialGroup()
                .addGroup(item_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(item_p2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(item_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(item_lbl_id)
                            .addComponent(item_lbl_name)
                            .addGroup(item_p2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(item_lbl_price)))
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, item_p2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(item_btn_reset)
                        .addGap(30, 30, 30)))
                .addGroup(item_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(item_p2Layout.createSequentialGroup()
                        .addGroup(item_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(item_p2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(item_txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addComponent(item_lbl_Qnt))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, item_p2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(item_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(item_p2Layout.createSequentialGroup()
                                        .addComponent(item_txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(item_lbl_category))
                                    .addGroup(item_p2Layout.createSequentialGroup()
                                        .addComponent(item_txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(32, 32, 32)
                        .addGroup(item_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(item_dropdown_category, 0, 214, Short.MAX_VALUE)
                            .addComponent(item_spinner_qnt))
                        .addGap(8, 8, 8))
                    .addGroup(item_p2Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(item_btn_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(item_btn_edit)
                        .addGap(98, 98, 98)
                        .addComponent(item_btn_delete)))
                .addGap(81, 81, 81))
        );
        item_p2Layout.setVerticalGroup(
            item_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item_p2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(item_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item_lbl_id)
                    .addComponent(item_txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item_lbl_Qnt)
                    .addComponent(item_spinner_qnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(item_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item_lbl_name)
                    .addComponent(item_txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item_lbl_category)
                    .addComponent(item_dropdown_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(item_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item_txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item_lbl_price))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addGroup(item_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item_btn_reset)
                    .addComponent(item_btn_add)
                    .addComponent(item_btn_edit)
                    .addComponent(item_btn_delete))
                .addGap(37, 37, 37))
        );

        item_lbl_id.getAccessibleContext().setAccessibleDescription("");
        item_txt_id.getAccessibleContext().setAccessibleName("Item ID");
        item_txt_name.getAccessibleContext().setAccessibleName("Item Name");
        item_txt_price.getAccessibleContext().setAccessibleName("item price");
        item_spinner_qnt.getAccessibleContext().setAccessibleName("Item Quantity");
        item_dropdown_category.getAccessibleContext().setAccessibleName("Item category");
        item_btn_edit.getAccessibleContext().setAccessibleName("item edit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(item_p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(item_p1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(item_p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(item_p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        item_p1.getAccessibleContext().setAccessibleName("item_p1");
        item_p1.getAccessibleContext().setAccessibleDescription("This panel will be at the top of the page, and it will have Item Page name and few buttons");
        item_p2.getAccessibleContext().setAccessibleName("item_p2");
        item_p2.getAccessibleContext().setAccessibleDescription("this panel will becontaining various form elements");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void item_btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_btn_addActionPerformed
         String[] item_arr = new String[8];
        int countInserted = 0;
        String item_id = item_txt_id.getText();
        String item_name = item_txt_name.getText();
        String item_price = item_txt_price.getText();
        String item_category = item_dropdown_category.getItemAt(item_dropdown_category.getSelectedIndex());
        //String item_category = item_dropdown_category.getSelectedItem()
        Object item_qnt;
        item_qnt = item_spinner_qnt.getValue();

        int item_id1 = Integer.parseInt(item_txt_id.getText());
        System.out.println("id " + item_id1);

        String item_name1 = item_txt_name.getText();
        System.out.println("name " + item_name1);

        Object item_qnt1;
        item_qnt1 = item_spinner_qnt.getValue();
        int item_qnt2 = Integer.parseInt(String.valueOf(item_qnt1));
        System.out.println("Quantity " + item_qnt2);

        int item_category1 = item_dropdown_category.getSelectedIndex();
        System.out.println("category " + item_category1);

        double item_price1 = Double.parseDouble(item_txt_price.getText());
        System.out.println("price " + item_price1);

        try {

            connection = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWD);
           //statement = connection.createStatement();

            //String sqlInsert = "INSERT INTO item_master(item_code,name,Quantity,category_id,price) VALUES (4,'',90,4,40.0)";
            //String sqlInsert = "INSERT INTO item_master(item_code,name,Quantity,category_id,price) VALUES (item_id1,item_name1,item_qnt2,item_category1,item_price1)";
            String sqlInsert = "INSERT INTO `item_master` (item_code,name,Quantity,category_id,price) VALUES (?,?,?,?,?)";
            
            
            PreparedStatement pstm = connection.prepareStatement(sqlInsert);
            pstm.setInt(1, item_id1);
            pstm.setString(2, item_name1);
            pstm.setInt(3, item_qnt2);
            pstm.setInt(4, item_category1);
            pstm.setDouble(5, item_price1);
            
            System.out.println("The SQL statement is: " + sqlInsert + "\n");  // Echo for debugging
            countInserted = pstm.executeUpdate();
            System.out.println(countInserted + " records inserted.\n");

        } catch (SQLException ex) {
            ex.printStackTrace();
        } finally {
            try {
                connection.close();
                //statement.close();
            } catch (SQLException ex) {
                Logger.getLogger(Add_items.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        item_arr[0] = item_id;
        item_arr[1] = item_name;
        item_arr[2] = item_price;
        item_arr[4] = String.valueOf(item_qnt);
        item_arr[5] = String.valueOf(item_category);
        //item_arr[6] = item_address;
        item_arr[6] = countInserted + " records inserted.\n";
        item_arr[7] = "\n Records inserted successfully";

        JOptionPane.showMessageDialog(this, item_arr);

        
    }//GEN-LAST:event_item_btn_addActionPerformed

    private void item_btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_btn_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_btn_editActionPerformed

    private void item_btn_dashbdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_btn_dashbdActionPerformed

        InventoryManagement obj = new InventoryManagement();
        obj.setVisible(true);
        setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_item_btn_dashbdActionPerformed

    private void item_dropdown_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_dropdown_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_dropdown_categoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_items().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton item_btn_add;
    private javax.swing.JButton item_btn_dashbd;
    private javax.swing.JButton item_btn_delete;
    private javax.swing.JButton item_btn_edit;
    private javax.swing.JButton item_btn_reset;
    private javax.swing.JComboBox<String> item_dropdown_category;
    private javax.swing.JLabel item_lbl_Qnt;
    private javax.swing.JLabel item_lbl_category;
    private javax.swing.JLabel item_lbl_id;
    private javax.swing.JLabel item_lbl_name;
    private javax.swing.JLabel item_lbl_price;
    private javax.swing.JLabel item_lbl_title;
    private javax.swing.JPanel item_p1;
    private javax.swing.JPanel item_p2;
    private javax.swing.JSpinner item_spinner_qnt;
    private javax.swing.JTextField item_txt_id;
    private javax.swing.JTextField item_txt_name;
    private javax.swing.JTextField item_txt_price;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
