/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorymanagement;

/**
 *
 * @author admin
 */
public class Bill_item extends javax.swing.JFrame {

    /**
     * Creates new form bill_item
     */
    public Bill_item() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bill1_p1 = new javax.swing.JPanel();
        bill1_lbl_title = new javax.swing.JLabel();
        bill1_p2 = new javax.swing.JPanel();
        bill1_lbl_itemId = new javax.swing.JLabel();
        bill1_lbl_qnt = new javax.swing.JLabel();
        bill1_btn_add = new javax.swing.JButton();
        bill1_btn_delete = new javax.swing.JButton();
        bill1_txt_itemId = new javax.swing.JTextField();
        bill1_txt_Qnt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        bill1_tbl = new javax.swing.JTable();
        bill1_p3 = new javax.swing.JPanel();
        bill1_btn_cancel = new javax.swing.JButton();
        bill1_btn_next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Billing Page");
        setResizable(false);

        bill1_p1.setBackground(new java.awt.Color(255, 255, 153));

        bill1_lbl_title.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bill1_lbl_title.setText("Bill Page");

        javax.swing.GroupLayout bill1_p1Layout = new javax.swing.GroupLayout(bill1_p1);
        bill1_p1.setLayout(bill1_p1Layout);
        bill1_p1Layout.setHorizontalGroup(
            bill1_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bill1_p1Layout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(bill1_lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bill1_p1Layout.setVerticalGroup(
            bill1_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bill1_p1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bill1_lbl_title)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        bill1_p2.setBackground(new java.awt.Color(255, 255, 204));

        bill1_lbl_itemId.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bill1_lbl_itemId.setText("Item ID");

        bill1_lbl_qnt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bill1_lbl_qnt.setText("Quantity");

        bill1_btn_add.setBackground(new java.awt.Color(255, 255, 153));
        bill1_btn_add.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bill1_btn_add.setText("ADD");

        bill1_btn_delete.setBackground(new java.awt.Color(255, 255, 153));
        bill1_btn_delete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bill1_btn_delete.setText("Delete");

        bill1_txt_itemId.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        bill1_txt_Qnt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout bill1_p2Layout = new javax.swing.GroupLayout(bill1_p2);
        bill1_p2.setLayout(bill1_p2Layout);
        bill1_p2Layout.setHorizontalGroup(
            bill1_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bill1_p2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bill1_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bill1_p2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bill1_btn_delete)
                        .addGap(18, 18, 18)
                        .addComponent(bill1_btn_add))
                    .addGroup(bill1_p2Layout.createSequentialGroup()
                        .addComponent(bill1_lbl_itemId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(bill1_txt_itemId, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bill1_p2Layout.createSequentialGroup()
                        .addComponent(bill1_lbl_qnt)
                        .addGap(18, 18, 18)
                        .addComponent(bill1_txt_Qnt)))
                .addGap(31, 31, 31))
        );
        bill1_p2Layout.setVerticalGroup(
            bill1_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bill1_p2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(bill1_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bill1_lbl_itemId)
                    .addComponent(bill1_txt_itemId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bill1_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bill1_lbl_qnt)
                    .addComponent(bill1_txt_Qnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bill1_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bill1_btn_add)
                    .addComponent(bill1_btn_delete))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        bill1_tbl.setBackground(new java.awt.Color(204, 255, 204));
        bill1_tbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bill1_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Sr No.", "Product Name", "Quantity", "Amount", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bill1_tbl);

        bill1_p3.setBackground(new java.awt.Color(255, 255, 153));

        bill1_btn_cancel.setBackground(new java.awt.Color(255, 255, 204));
        bill1_btn_cancel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bill1_btn_cancel.setText("Cancel");
        bill1_btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bill1_btn_cancelActionPerformed(evt);
            }
        });

        bill1_btn_next.setBackground(new java.awt.Color(255, 255, 204));
        bill1_btn_next.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bill1_btn_next.setText("Next");
        bill1_btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bill1_btn_nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bill1_p3Layout = new javax.swing.GroupLayout(bill1_p3);
        bill1_p3.setLayout(bill1_p3Layout);
        bill1_p3Layout.setHorizontalGroup(
            bill1_p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bill1_p3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(bill1_btn_cancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bill1_btn_next)
                .addContainerGap())
        );
        bill1_p3Layout.setVerticalGroup(
            bill1_p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bill1_p3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bill1_p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bill1_btn_cancel)
                    .addComponent(bill1_btn_next))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bill1_p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bill1_p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bill1_p3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bill1_p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bill1_p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bill1_p3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bill1_btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bill1_btn_cancelActionPerformed

        InventoryManagement obj = new InventoryManagement();
        obj.setVisible(true);
        setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_bill1_btn_cancelActionPerformed

    private void bill1_btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bill1_btn_nextActionPerformed
        // TODO add your handling code here:
        
        Bill_generate obj = new Bill_generate();
        obj.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_bill1_btn_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill_item().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bill1_btn_add;
    private javax.swing.JButton bill1_btn_cancel;
    private javax.swing.JButton bill1_btn_delete;
    private javax.swing.JButton bill1_btn_next;
    private javax.swing.JLabel bill1_lbl_itemId;
    private javax.swing.JLabel bill1_lbl_qnt;
    private javax.swing.JLabel bill1_lbl_title;
    private javax.swing.JPanel bill1_p1;
    private javax.swing.JPanel bill1_p2;
    private javax.swing.JPanel bill1_p3;
    private javax.swing.JTable bill1_tbl;
    private javax.swing.JTextField bill1_txt_Qnt;
    private javax.swing.JTextField bill1_txt_itemId;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
