/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorymanagement;

/**
 *
 * @author admin
 */
public class Bill_generate extends javax.swing.JFrame {

    /**
     * Creates new form bill_generate
     */
    public Bill_generate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bill2_p1 = new javax.swing.JPanel();
        bill2_lbl_title = new javax.swing.JLabel();
        bill2_p3 = new javax.swing.JPanel();
        bill2_btn_back = new javax.swing.JButton();
        bill2_btn_billgenerate = new javax.swing.JButton();
        bill2_btn_dashbd = new javax.swing.JButton();
        bill2_p2 = new javax.swing.JPanel();
        bill2_lbl_title2 = new javax.swing.JLabel();
        bill2_lbl_custNm = new javax.swing.JLabel();
        bill2_lbl_contNo = new javax.swing.JLabel();
        bill2_btn_add = new javax.swing.JButton();
        bill2_txt_custNm = new javax.swing.JTextField();
        bill2_txt_mobileNo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bill Page");
        setResizable(false);

        bill2_p1.setBackground(new java.awt.Color(255, 255, 153));

        bill2_lbl_title.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        bill2_lbl_title.setText("Billing Page");

        javax.swing.GroupLayout bill2_p1Layout = new javax.swing.GroupLayout(bill2_p1);
        bill2_p1.setLayout(bill2_p1Layout);
        bill2_p1Layout.setHorizontalGroup(
            bill2_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bill2_p1Layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(bill2_lbl_title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bill2_p1Layout.setVerticalGroup(
            bill2_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bill2_p1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bill2_lbl_title, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addContainerGap())
        );

        bill2_p3.setBackground(new java.awt.Color(255, 255, 153));

        bill2_btn_back.setBackground(new java.awt.Color(255, 255, 204));
        bill2_btn_back.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bill2_btn_back.setText("Back");
        bill2_btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bill2_btn_backActionPerformed(evt);
            }
        });

        bill2_btn_billgenerate.setBackground(new java.awt.Color(255, 255, 204));
        bill2_btn_billgenerate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bill2_btn_billgenerate.setText("Generate Bill");

        bill2_btn_dashbd.setBackground(new java.awt.Color(255, 255, 204));
        bill2_btn_dashbd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bill2_btn_dashbd.setText("Dashboard");
        bill2_btn_dashbd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bill2_btn_dashbdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bill2_p3Layout = new javax.swing.GroupLayout(bill2_p3);
        bill2_p3.setLayout(bill2_p3Layout);
        bill2_p3Layout.setHorizontalGroup(
            bill2_p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bill2_p3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(bill2_btn_back)
                .addGap(146, 146, 146)
                .addComponent(bill2_btn_billgenerate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(bill2_btn_dashbd)
                .addGap(56, 56, 56))
        );
        bill2_p3Layout.setVerticalGroup(
            bill2_p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bill2_p3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(bill2_p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bill2_btn_back)
                    .addComponent(bill2_btn_billgenerate)
                    .addComponent(bill2_btn_dashbd))
                .addContainerGap())
        );

        bill2_p2.setBackground(new java.awt.Color(255, 255, 204));

        bill2_lbl_title2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bill2_lbl_title2.setText("Customer details");

        bill2_lbl_custNm.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bill2_lbl_custNm.setText("Customer Name");

        bill2_lbl_contNo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bill2_lbl_contNo.setText("Contact Number");

        bill2_btn_add.setBackground(new java.awt.Color(255, 255, 153));
        bill2_btn_add.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bill2_btn_add.setText("ADD");

        bill2_txt_custNm.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        bill2_txt_mobileNo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout bill2_p2Layout = new javax.swing.GroupLayout(bill2_p2);
        bill2_p2.setLayout(bill2_p2Layout);
        bill2_p2Layout.setHorizontalGroup(
            bill2_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bill2_p2Layout.createSequentialGroup()
                .addGroup(bill2_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bill2_p2Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(bill2_lbl_title2))
                    .addGroup(bill2_p2Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(bill2_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bill2_lbl_custNm)
                            .addComponent(bill2_lbl_contNo))
                        .addGap(69, 69, 69)
                        .addGroup(bill2_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bill2_txt_custNm)
                            .addComponent(bill2_txt_mobileNo, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)))
                    .addGroup(bill2_p2Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(bill2_btn_add)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bill2_p2Layout.setVerticalGroup(
            bill2_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bill2_p2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bill2_lbl_title2)
                .addGap(18, 18, 18)
                .addGroup(bill2_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bill2_lbl_custNm)
                    .addComponent(bill2_txt_custNm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(bill2_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bill2_lbl_contNo)
                    .addComponent(bill2_txt_mobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bill2_btn_add)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bill2_p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bill2_p3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bill2_p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bill2_p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bill2_p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bill2_p3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bill2_btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bill2_btn_backActionPerformed
        // TODO add your handling code here:
        
        Bill_item obj = new Bill_item();
        obj.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_bill2_btn_backActionPerformed

    private void bill2_btn_dashbdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bill2_btn_dashbdActionPerformed
        // TODO add your handling code here:
        
        InventoryManagement obj = new InventoryManagement();
        obj.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_bill2_btn_dashbdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill_generate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill_generate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill_generate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill_generate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill_generate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bill2_btn_add;
    private javax.swing.JButton bill2_btn_back;
    private javax.swing.JButton bill2_btn_billgenerate;
    private javax.swing.JButton bill2_btn_dashbd;
    private javax.swing.JLabel bill2_lbl_contNo;
    private javax.swing.JLabel bill2_lbl_custNm;
    private javax.swing.JLabel bill2_lbl_title;
    private javax.swing.JLabel bill2_lbl_title2;
    private javax.swing.JPanel bill2_p1;
    private javax.swing.JPanel bill2_p2;
    private javax.swing.JPanel bill2_p3;
    private javax.swing.JTextField bill2_txt_custNm;
    private javax.swing.JTextField bill2_txt_mobileNo;
    // End of variables declaration//GEN-END:variables
}
